require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# Override Firebase SDK Version
$FirebaseSDKVersion = '7.0.0'

platform :ios, '10.0'

target 'instagramclone' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  # add the Firebase pod for Google Analytics
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Core'

  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app/'

  # pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  # pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  #   'FaceDetectorMLKit'
  # ]

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  use_react_native!(:path => config["reactNativePath"])

  target 'instagramcloneTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'instagramclone-tvOS' do
  # Pods for instagramclone-tvOS

  target 'instagramclone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
